steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kallisto-pipeline:$TAG_NAME', '.']
  dir: 'kallisto-pipeline'
timeout: '5m'
images: ['gcr.io/$PROJECT_ID/kallisto-pipeline:$TAG_NAME']
